@startuml
'https://plantuml.com/sequence-diagram

interface Tuiles <<interface>>{

}

class TuileT implements Tuiles{
}

class TuileDroite implements Tuiles{
}

class TuileAngle implements Tuiles{
}

class Objectif{
    + <<Create>>Objectif(nomObj : String, posX : Integer, posY : Integer)
}

class Plateau{
    <<Create>>Plateau()
}

class Joueur{
    - objectifActuel: Objectif
    + getNbObjRecup(): Integer
    + getNbObjRestant(): Integer
}


@enduml