@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

package Model {
    abstract Tile {
        +<<Create>>Tile()
        +rotate(): void
        +getType(): String
    }
    class TileT extends Tile {
        +rotate(): void
        +getType(): Integer
    }
    class TileLine extends Tile {
        +rotate(): void
        +getType(): Integer
    }
    class TileL extends Tile {
        +rotate(): void
        +getType(): Integer
    }

    class TileFactory {
        +<<Create>>TileFactory()
        +createTileL(): Tile
        +createTileT(): Tile
        +createTileLine(): Tile
    }

    class Board {
        -tiles: List<Tile>
        -extraTile: Tile
        +initializeBoard(): void
        +pushRow(rowIndex: Integer, direction: Integer): void
        +pushColumn(colIndex: Integer, direction: Integer): void
    }

    class Objective {
        -id: Integer
        -position: Integer
    }

    class Player {
        -num: Integer
        -currentTile: Tile
        -currentObjective: Objective
        -completedObjectives: List<Objective>
        +move(direction: Integer): boolean
    }

    class Game {
        -players: List<Player>
        -board: Board
        +start(): void
        +end(): void
        +nextTurn(): void
    }

    interface GameObserver {
        +update(game: Game): void
    }
}

package View {
    class MainScreen {
        +update(game: Game): void
        +displayBoard(board: Board): void
        +displayPlayerInfo(players: List<Player>): void
    }
    class EndScreen {
        +displayWinner(player: Player): void
    }
}

package Controller {
    class GameController {
        +game: Game
        +rotateExtraTile(direction: String): void
        +pushRow(rowIndex: Integer, direction: Integer): void
        +pushColumn(colIndex: Integer, direction: Integer): void
        +movePlayer(player: Player, direction: Integer): void
    }
}

TileFactory ..> Tile : <<uses>>
TileFactory ..> TileT : <<uses>>
TileFactory ..> TileL : <<uses>>
TileFactory ..> TileLine : <<uses>>

Board ..> TileFactory : <<uses>>
Game o-- Board
Game o-- Player
Player ..> Objective
Game ..|> GameObserver
Board o-- Tile : > <<uses>>

GameObserver <|-- MainScreen
GameObserver <|-- EndScreen

GameController ..> Game
GameController ..> MainScreen

@enduml
