@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

package model
{
    abstract Tile <<abstract>>
    {
        - isOpenTop : Boolean
        - isOpenRight : Boolean
        - isOpenBottom : Boolean
        - isOpenLeft : Boolean
        + <<Create>>Tile(isOpenRight : Boolean, isOpenLeft : Boolean, isOpenTop : Boolean, isOpenBottom : Boolean)
        + getPosition() : position
        + getMovable() : Boolean
        + getIsOpenRight() : Boolean
        + getIsOpenLeft() : Boolean
        + getIsOpenTop() : Boolean
        + getIsOpenBottom() : Boolean
        + setPosition(position : Position)
        + setOpenRight(isOpenRight : Boolean)
        + setOpenLeft(isOpenLeft : Boolean)
        + setOpenTop(isOpenTop : Boolean)
        + setOpenBottom(isOpenBottom : Boolean)
        + addObserver(tileObserver : TileObserver)
        + notifyRotate(direction : Direction)
        {abstract} + rotate(direction : Direction)
        {abstract} + getType() : TypeTile
        {abstract} + output() : String
    }

    class TileT extends Tile
    {
        + <<Create>>TileT(isOpenRight : Boolean, isOpenLeft : Boolean, isOpenTop : Boolean, isOpenBottom : Boolean)
        + rotate(direction : Direction)
        + getType() : TypeTile
        + output() : String
    }

    class TileLine extends Tile
    {
        + <<Create>>TileLine(isOpenRight : Boolean, isOpenLeft : Boolean, isOpenTop : Boolean, isOpenBottom : Boolean)
        + rotate(direction : Direction)
        + getType() : TypeTile
        + output() : String
    }

    class TileAngle extends Tile
    {
        + <<Create>>TileAngle(isOpenRight : Boolean, isOpenLeft : Boolean, isOpenTop : Boolean, isOpenBottom : Boolean)
        + rotate(direction : Direction)
        + getType() : TypeTile
        + output() : String
    }

    class TileFactory
    {
        + <<Create>>TileFactory()
        + createTileAngle() : Tile
        + createTileT() : Tile
        + createTileLine() : Tile
    }

    enum Direction <<enum>>
    {
        TOP
        BOTTOM
        LEFT
        RIGHT
    }

    enum TypeTile <<enum>>
    {
        T
        ANGLE
        LINE
    }

    class Board
    {
        + <<Create>> Board()
        + addObserver(observer : BoardObserver)
        + initializeBoard()
        + getTiles() : Tile[][]
        + shuffleTiles() : Tile[*]
        + pushRowLeft(rowIndex : Integer)
        + pushRowRight(rowIndex : Integer)
        + pushColumnTop(colIndex : Integer)
        + pushColumnBottom(colIndex : Integer)
        + setTileAt(position : Position)
        + addObserver(boardObserver : BoardObserver)
        + notifyObserversUpdatePushRow(index : Integer, direction : Direction)
        + notifyObserversUpdatePushColumn(index : Integer, direction : Direction)
        + getTile(position : Position) : Tile
    }

    class Objective
    {
        - nameObjective : String
        + <<Create>>Objective(position : Position, nameObjective : String)
        + getPosition() : Position
        + setPosition(position : Position)
    }

    class Player
    {
        - numberReclaimedObjectives : Integer
        - numberRemainingObjectives : Integer
        + <<Create>>Player(position : Position, objectives : Objective[*])
        + addObserver(observer : PlayerObserver)
        + getPosition() : Position
        + getFirstPosition() : Position
        + setPosition(position : Position)
        + isWinner() : Boolean
        + reclaimedCurrentObjective() : Boolean
        + notifyObserversUpdatePosition()
        + notifyObserversUpdateObjective()
        + output() : String
    }

    class Game
    {
        + <<Create>>Game(board : Board, players : Player[*], extraTile : Tile)
        + switchCurrentPlayer()
        + getCurrentPlayer() : Player
        + movePlayer(player : Player, direction : Direction)
        + getExtraTile : Tile
        + initObjectives()
        + dealObjectivesToPlayer()
        + getObjectives()
        + getPlayersOnRow(index : Integer) : Player[*]
        + getPlayersOnColumn(index : Integer) : Player[*]
        + pushRow(row : Integer, direction : Direction)
        + pushColumn(column : Integer, direction : Direction)
        + getPlayers() : Player[*]
        + getBoard() : Board
    }

    class Position
    {
        + <<Create>> Position(positionX : Integer, positionY : Integer)
        - positionX : Integer
        - positionY : Integer
        + getPosition() : Position
        + getX() : Integer
        + getY() : Integer
        + setX(x : Integer)
        + setY(y : Integer)
        + equals(other : Position) : Boolean
    }

    class BoardObserver<<interface>>
    {
        + {abstract}updatePushTile(index : Integer, direction : Direction)
        + {abstract}updateBoardState()
    }

    class PlayerObserver<<interface>>
    {
        + {abstract}updatePlayerPosition(position : Position, player: Player)
        + {abstract}updateObjectiveState(player: Player, reclaimedObjectives : Integer, remainingObjectives : Integer)
    }

    class TileObserver<<interface>>
    {
        + {abstract}updateRotate(direction : Direction)
    }
}

package View
{
   class BoardTextManager implements model.BoardObserver
   {
        + updatePushRow(index : Integer, direction : Direction)
        + updatePushColumn(index : Integer, direction : Direction)
   }

   class PlayerTextManager implements model.PlayerObserver
  {
       + updatePosition(position : Position)
  }

  class TileTextManager implements model.TileObserver
 {
      + updateRotate(direction : Direction, tile : Tile)
 }

   class GameDisplay{
       <<Create>>GameDisplay(game : Game)
       + Display()
   }

   class Display{
       + Display(gameController : GameController, game : Game)
       + initializeBoard(tiles : Tile[][], players : Player[*])
       + addPushButtons(gameController : GameController, game : Game)
       + updateBoard(game : Game)
       + rotateExtraTile()
       + updateExtraTile(tile : Tile)
       + moveAndUpdate(gameController : GameController, direction : Direction, game : Game)
       + pathImgOfTile(tile : Tile) : String
       + rotate(original : BufferedImage, angle : Double) : BufferedImage
   }

   class EndScreen implements model.BoardObserver, model.PlayerObserver
   {
        + displayWinner(player: Player)
   }
}

package Controller
{
    class GameController
    {
        + <<Create>>GameController(game : Game)
        + rotateExtraTile(sens : Integer)
        + pushRow(rowIndex : Integer, direction : Direction)
        + pushColumn(colIndex : Integer, direction : Direction)
        + movePlayer(player : Player, direction : Direction)
        + endOfRound()
    }

    class LabyrintheApp
    {
        + main()
    }
}

TileFactory ..> Tile : <<uses>>
TileFactory ..> TileT : <<uses>>
TileFactory ..> TileAngle : <<uses>>
TileFactory ..> TileLine : <<uses>>

LabyrintheApp ..> Board : <<uses>>
LabyrintheApp ..> Player : <<uses>>
LabyrintheApp ..> Tile : <<uses>>
LabyrintheApp ..> Display : <<uses>>
LabyrintheApp ..> Game : <<uses>>
LabyrintheApp ..> GameDisplay : <<uses>>
LabyrintheApp ..> PlayerTextManager : <<uses>>
LabyrintheApp ..> BoardTextManager : <<uses>>
LabyrintheApp ..> TileTextManager : <<uses>>

Tile ..> TypeTile : <<uses>>
TileT ..> TypeTile : <<uses>>
TileAngle ..> TypeTile : <<uses>>
TileLine ..> TypeTile : <<uses>>

Player ..> Direction : <<uses>>

Game ..> Tile : <<uses>>

Tile o--> "  1\n - position" Position
Player o--> "1\n- position" Position
Player o--> "  1\n       - firstPosition" Position
Objective o--> "1\n- position" Position


Board ..> TileFactory : <<uses>>
Game o--> "  1\n - board" Board
Game o--> "  1\n - extraTile" Tile
Game *--> "  4\n - player" Player
GameDisplay o--> "  1\n - game" Game
Board o--> "  *\n - observers" BoardObserver
Player o--> "  *\n - observers" PlayerObserver
Tile o--> "  *\n - observers" TileObserver

Player o-u-> "1\n- currentObjective" Objective
Player o-u-> "0 .. *\n- objectives" Objective
Board *--> "49 \n- tiles" Tile : > contains
Board o--> "1\n- extraTile" Tile : > contains
Board *--> "24\n- objectives" Objective
Board o--> "4\n- pions" Player

Display o--> "1n- gameController" GameController
Display o--> "1n- game" Game
GameController o--> "1\n- game" Game

@enduml